## Import Necessary Libraries

In [4]:
import warnings
import tensorflow
import numpy as np
import pandas as pd

from tensorflow import keras
warnings.filterwarnings('ignore')
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

## Loading Data

In [5]:
df = pd.DataFrame([
    [8,8,4],
    [7,9,5],
    [6,10,6],
    [5,12,7]
],
    columns=['cgpa', 'profile_score', 'lpa'])

In [6]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [8]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.get_weights()

[array([[-0.04262412,  0.50639296],
        [-0.6378739 , -1.0400119 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.9083239],
        [-1.328494 ]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
new_weights = [np.array([[0.1, 0.1],[0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)
              ]

In [12]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [16]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 1.4575
Epoch 2/75
4/4 [==============================] - 0s 5ms/step - loss: 1.4117
Epoch 3/75
4/4 [==============================] - 0s 4ms/step - loss: 1.3352
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 1.3223
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 1.2783
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 1.2465
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 1.2462
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 1.2037
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 1.1894
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 1.1754
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 1.1498
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 1.1249
Epoch 13/75
4/4 [==============================] - 0s 4ms/step - loss: 1.

In [17]:
model.get_weights()

[array([[0.36150983, 0.36150983],
        [0.41016394, 0.41016394]], dtype=float32),
 array([0.29354522, 0.29354522], dtype=float32),
 array([[0.39806512],
        [0.39806512]], dtype=float32),
 array([0.21659741], dtype=float32)]