### Import Necessary Libraries

In [4]:
import warnings
import tensorflow
import numpy as np
import pandas as pd

from tensorflow import keras
warnings.filterwarnings('ignore')
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

### Loading Data

In [5]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [6]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [8]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.get_weights()

[array([[-0.21715927, -0.8795951 ],
        [-0.9638812 ,  0.19656193]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.1903714 ],
        [0.21450484]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
new_weights = [np.array([[0.1, 0.1],[0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)
              ]

In [12]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [16]:
model.fit(df.iloc[:,0:-1].values, df['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6929
Epoch 2/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6929
Epoch 3/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6929
Epoch 4/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6929
Epoch 5/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6930
Epoch 6/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6928
Epoch 7/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6928
Epoch 8/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6929
Epoch 9/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6928
Epoch 10/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6928
Epoch 11/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6928
Epoch 12/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6929
Epoch 13/50
4/4 [==============================] - 0s 4ms/step - loss: 0.