# Linear Algebra
`The branch of mathematics that deals with the theory of systems of linear equations, matrices, vector spaces, and linear transformations.`


In [1]:
# ! pip install numpy
import numpy as np

## Vector - 
**_*`A vector is a quantity which has both magnitude and direction.`*_**
****

$$ Row Vector = \begin{bmatrix} 3 & 2 & -1 \end{bmatrix}$$

$$ Column Vector = \begin{bmatrix} 3 \\ 2 \\ -1 \end{bmatrix}$$

In [2]:
# row vector - target
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
# column vector - features
np.arange(1, 8).reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

## Vector Ops - 
**_*`A vector is a quantity which has both magnitude and direction.`*_**
****
| Operation | X | Y | Output |
| :-------- | ---: | ::--- | ----::|
| Vector Adition | $$ x = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix} $$ | $$ y = \begin{bmatrix} 5 \\ 3 \\ 0 \end{bmatrix}$$ | $$ output = \begin{bmatrix} 3 + 5 \\ 2 + 3 \\ 1 + 0 \end{bmatrix}= \begin{bmatrix} 8 \\ 5 \\ 1 \end{bmatrix} $$ |
| Vector Subtraction | $$ x = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix} $$ | $$ y = \begin{bmatrix} 5 \\ 3 \\ 0 \end{bmatrix}$$ | $$ output = \begin{bmatrix} 3 - 5 \\ 2 - 3 \\ 1 - 0 \end{bmatrix}= \begin{bmatrix} -2 \\ -1 \\ 1 \end{bmatrix} $$ |
| Vector Multiplication | $$ x = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix} $$ | $$ y = \begin{bmatrix} 5 \\ 3 \\ 1 \end{bmatrix}$$ | $$ output = \begin{bmatrix} 3 \times 5 \\ 2\times3 \\ 1\times0 \end{bmatrix}= \begin{bmatrix} 15 \\ 6 \\ 0 \end{bmatrix} $$ |
| Vector Division | $$ x = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix} $$ | $$ y = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix}$$ | $$ output = \begin{bmatrix} \frac33 \\ \frac22 \\ \frac11 \end{bmatrix}= \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} $$ |
| Scaler-Vector Operations | $$ x = 2 $$ | $$ y = \begin{bmatrix} 5 \\ 3 \\ 1 \end{bmatrix}$$ | $$ output = \begin{bmatrix} 2 \times 5 \\ 2\times3 \\ 2\times0 \end{bmatrix}= \begin{bmatrix} 10 \\ 6 \\ 0 \end{bmatrix} $$ |

In [4]:
# create vectors or arrays
x = np.array([3, 2, 1])
y = np.array([5, 3, 0])

In [5]:
# vector addition
x + y
np.add(x, y)

array([8, 5, 1])

In [6]:
# vector subtraction
x - y
np.subtract(x, y)

array([-2, -1,  1])

In [7]:
# multiplication
x * y
np.multiply(x, y)

array([15,  6,  0])

In [8]:
# division
y = np.array([5, 3, 1])
x / y
x // y
np.divide(x, y)

array([0.6       , 0.66666667, 1.        ])

In [9]:
# divmod
np.divmod(x, y)

(array([0, 0, 1]), array([3, 2, 0]))

In [10]:
# scaler-vector ops
m = 0.5
m*x

array([1.5, 1. , 0.5])

## Matrices -
**_*`A matrix is an m × n array of scalars from a given field F. The individual values in the matrix are called entries`*_**
****

| Type | Example |
| :---- | ---------: |
| Square Matrix | $$  A =\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6 \\7 & 8 & 9\end{bmatrix}$$ |
| Lower Triangle Matrix | $$  B =\begin{bmatrix}1 & 0 & 0 \\4 & 5 & 0 \\7 & 8 & 9\end{bmatrix}$$ |
| Upper Triangle Matrix | $$  C =\begin{bmatrix}1 & 6 & 7 \\0 & 5 & 8 \\0 & 0 & 9\end{bmatrix}$$ |
| Diagonal Matrix | $$  D =\begin{bmatrix}1 & 0 & 0 \\0 & 5 & 0 \\0 & 0 & 9\end{bmatrix}$$ |
| Unit/Identity Matrix | $$  I =\begin{bmatrix}1 & 0 & 0 \\0 & 1 & 0 \\0 & 0 & 1\end{bmatrix}$$ |
| Null or ZeroMatrix | $$  I =\begin{bmatrix}0 & 0 & 0 \\0 & 0 & 0 \\0 & 0 & 0\end{bmatrix}$$ |

In [11]:
# square matrix
np.empty(shape=(3,3))
np.empty(shape=(2,2))

array([[2.12199579e-314, 1.41324920e-311],
       [4.94065646e-321, 8.28942550e-317]])

In [12]:
np.empty(shape=(2,3)) # not a square matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# lower triangular matrix
np.tril(np.arange(1, 37).reshape(6,6), k=0)

array([[ 1,  0,  0,  0,  0,  0],
       [ 7,  8,  0,  0,  0,  0],
       [13, 14, 15,  0,  0,  0],
       [19, 20, 21, 22,  0,  0],
       [25, 26, 27, 28, 29,  0],
       [31, 32, 33, 34, 35, 36]])

In [14]:
# upper triangular matrix
np.triu(np.arange(1, 37).reshape(6,6), k=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  8,  9, 10, 11, 12],
       [ 0,  0, 15, 16, 17, 18],
       [ 0,  0,  0, 22, 23, 24],
       [ 0,  0,  0,  0, 29, 30],
       [ 0,  0,  0,  0,  0, 36]])

In [15]:
# make this as diagonal matrix
mat = np.arange(1, 37).reshape(6,6)
mat = np.tril(mat, k=0)
mat = np.triu(mat, k=0)
mat

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 22,  0,  0],
       [ 0,  0,  0,  0, 29,  0],
       [ 0,  0,  0,  0,  0, 36]])

In [16]:
# extract only diagonal values
mat.diagonal()
np.diag(mat)

array([ 1,  8, 15, 22, 29, 36])

In [17]:
mat = np.arange(1, 37).reshape(6,6)
mat = np.tril(mat, k=1)
mat = np.triu(mat, k=1)
mat

array([[ 0,  2,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0],
       [ 0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0, 23,  0],
       [ 0,  0,  0,  0,  0, 30],
       [ 0,  0,  0,  0,  0,  0]])

In [18]:
# when diagonal is in different place
mat.diagonal(1)

array([ 2,  9, 16, 23, 30])

In [19]:
# identity Matrix
I = np.eye(4,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# zeros-matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
1 + 0

1

In [23]:
4 * 1

4

## Dot vs Cross Product
****
| Dot Product | Cross Product |
| :---------- | :------------ |
| <img src="matrix-multiply-a.svg" style="height:160px, width:160px" /> | <img src="matrix-cross.png" style="height:160px, width:160px" /> |


In [24]:
x = np.array(
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
)
y = np.array(
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
)

In [25]:
# dot
np.dot(x, y)

array([[ 58,  64],
       [139, 154]])

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [27]:
# cross
np.cross(a, b)

array([-3,  6, -3])

## Matrix Ops - 
**_*``*_**
****
| Operation | Example |
| :-------- | :-- |
| **Matrix Addition** | <img src="matrix-addition.svg" style="height:160px, width:160px" /> |
| **Matrix Transpose** | <img src="matrix-transpose.gif" style="height:160px, width:160px" /> |
| **Scaler-Matrix Operations** | <img src="matrix-multiply-constant.svg" style="height:160px, width:160px" /> | 
| **Matrix Multiplication** | <img src="matrix-multiply-a.svg" style="height:160px, width:160px" /> |
| **Matrix Multiplication** | <img src="Matrix-graphic-2.svg" style="height:300px" /> |
| **Matrix Multiplication Condition** | <img src="matrix-multiply-rows-cols.svg" style="height:160px, width:160px"> |


In [28]:
# addition
x = np.array([[3, 8], [4,6]])
y = np.array([[4, 0], [1, -9]])
x+y
np.add(x, y)

array([[ 7,  8],
       [ 5, -3]])

In [29]:
# Transpose
matrix = np.array([[6, 4, 24 ], [1, -9, 8]])
matrix.transpose()

array([[ 6,  1],
       [ 4, -9],
       [24,  8]])

In [30]:
# multiply
mat = np.array([[4, 9], [1, -9]])
scaler = 2
scaler*mat
np.multiply(scaler, mat)

array([[  8,  18],
       [  2, -18]])

In [31]:
m = np.array(
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
)
p = np.array(
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
)

In [32]:
# matrix multiplication
m@p
np.matmul(m, p)

array([[ 58,  64],
       [139, 154]])

## Solve Equations on Vectors and Matrices
****
| Equation | w | X | b |
| :-------- | ---: | ::--- | ----::|
| $$ y = wx + b $$ | $$ w = 2.0 $$ | $$ X = \begin{bmatrix} 5.0 \\ 3.0 \\ 2.0 \end{bmatrix}$$ | $$ b = 0.5 $$ |
|wrong $$  y = wx + b $$ | $$ w = \begin{bmatrix} 1.0&2.0 \end{bmatrix} $$ | $$ X = \begin{bmatrix} 5.0&6.0 \\ 3.0 & 4.0 \\ 2.0 & 1.0 \end{bmatrix}$$ | $$ b = 0.5 $$ |
| $$ y = wx + b $$ | $$ w = \begin{bmatrix} 1.0&2.0 \end{bmatrix} $$ | $$ X = \begin{bmatrix} 5.0&3.0&2.0 \\ 6.0&4.0&1.0 \end{bmatrix}$$ | $$ b = 0.5 $$ |

In [33]:
# scaler
w = 2.0
b = 0.5
x = 20

y = w*x + b
y

40.5

In [34]:
# on vectors - numpy does this using broadcasting
# w*x + b
# [2.0, 2.0, 2.0] * [5.0, 3.0, 2.0] + [0.5, 0.5, 0.5]

w = 2.0
b = 0.5
x = np.array([5.0, 3.0, 2.0])

y = w*x + b
y

array([10.5,  6.5,  4.5])

In [35]:
# on vectors - numpy does this using broadcasting
# w*x + b
# [2.0, 2.0, 2.0] * [5.0, 3.0, 2.0] + [0.5, 0.5, 0.5]

w = np.array([1.0, 2.0])
b = 0.5
x = np.array([[5.0, 3.0, 2.0], [6.0, 4.0, 1.0]])

y = np.dot(w, x) + b
y

array([17.5, 11.5,  4.5])

In [36]:
np.sum(w*x.transpose(), axis=1) + b

array([17.5, 11.5,  4.5])

In [37]:
w.shape

(2,)

In [38]:
x.shape

(2, 3)

In [39]:
np.dot?

Call signature:  np.dot(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function dot>
Docstring:      
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    Fi

## Determinant Of Matrix
****
****
| Example | det(M) > 1 | det(M) = 1 | det(M) < 1 | det(M) = 0|
| :---------- | :------------ | :---------- | :------------ |:------------ 
| | If a matrix stretches things out, then its determinant is greater than 1. | If a matrix doesn't stretch things out or squeeze them in, then its determinant is exactly 1. An example of this is a rotation. | If a matrix squeezes things in, then its determinant is less than 1. | Some matrices shrink space so much they actually flatten the entire grid on to a single line.then its determinant is exactly 0.
| <img src="determinant-g1.png" style="height:160px, width:160px" /> | <img src="determinant-g11.png" style="height:160px, width:160px" /> | <img src="determinant-e1.png" style="height:160px, width:160px" />| <img src="determinant-l1.png" style="height:160px, width:160px" /> |<img src="determinant-0.png" style="height:160px, width:160px" /> |

<img src="determinant-calc.png" style="height:160px, width:160px" />

In [40]:
from numpy import linalg

In [41]:
mat = np.random.random((3,3))
mat2 = np.random.random((4,4))

In [42]:
linalg.det(mat)

-0.12374018886900266

## <a href="https://www.cuemath.com/algebra/eigenvectors/">Eigen Values and Eigen Vectors</a>

In [43]:
mat3 = np.array([[5, 4], [1,2]])
mat3

array([[5, 4],
       [1, 2]])

In [44]:
linalg.eig(mat3)

EigResult(eigenvalues=array([6., 1.]), eigenvectors=array([[ 0.9701425 , -0.70710678],
       [ 0.24253563,  0.70710678]]))

In [45]:
linalg.eigh

<function eigh at 0x0000029A374BD070>

## L1 and L2 Norm

In [46]:
mat3

array([[5, 4],
       [1, 2]])

In [47]:
linalg.norm(mat3[0])

6.4031242374328485

In [48]:
# L1 norm
linalg.norm(mat3, ord=1)

6.0

In [49]:
# L2 norm
linalg.norm(mat3[0], ord=2)

6.4031242374328485

## <a href="https://www.geeksforgeeks.org/singular-value-decomposition-svd/">Singular Value Decomposition</a>

In [50]:
U, S, V = linalg.svd(mat3)

In [51]:
U

array([[-0.95149336, -0.30766928],
       [-0.30766928,  0.95149336]])

In [52]:
S

array([6.7233625 , 0.89241061])

In [53]:
V


array([[-0.75336353, -0.65760429],
       [-0.65760429,  0.75336353]])

## <a href="https://numpy.org/doc/stable/reference/generated/numpy.einsum.html">EienSum</a>

In [54]:
mat3

array([[5, 4],
       [1, 2]])

In [55]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [56]:
# vector sum
np.einsum('i->', v1)

6

In [57]:
# extract diagonal
np.einsum('ii->i', mat3)

array([5, 2])

In [58]:
# diagonal sum
np.einsum('ii->', mat3)

7

In [59]:
# row sum
np.einsum('ij->j', mat3)

array([6, 6])

In [60]:
# transpose
np.einsum('ij->ji', mat3)

array([[5, 1],
       [4, 2]])

In [61]:
# dot product
np.einsum('i,i->', v1, v2)

32

In [62]:
# matrix multiplication
mat3, mat3

(array([[5, 4],
        [1, 2]]),
 array([[5, 4],
        [1, 2]]))

In [63]:
np.einsum('ik, kj->ij', mat3, mat3)

array([[29, 28],
       [ 7,  8]])

In [64]:
mat = [[0,0], [0,0]]
for i in range(len(mat3)):
    for j in range(len(mat3[0])):
        for k in range(len(mat3)):
            mat[i][j] += mat3[i, k]*mat3[k, j]
    

In [65]:
mat

[[29, 28], [7, 8]]